### ISSUE TITLE
Add agent.documentation to improve consumer interactions

### ISSUE THREAD

**Issue by bvandewe** [d-clare/specification#2]
### What would you like to be added?

It might be useful for end-users to consult some kind of description of what an agent does and how to interact with it. 

For example, if my `weatherForecastProvider` returns the forecast given a city name, it'd be useful for consumers to know that so they dont need to write a longer prompt than just a city name...

In "software-related" terms, Its almost like the signature and documentation of an agent if an agent was a simple function. In contrast, however, the input/output documentation could be declared in natural language terms instead of rigid source code.

### Proposal(s):

```yaml
agent:
  name: weatherForecastProvider
  documentation:
    input: A city name (optional: A country, a duration in days)
    output: The weather forecast for the given city (defaults to duration of 5 days)
```

### Community Notes

* Please vote by adding a 👍 reaction to the feature to help us prioritize.
* If you are interested to work on this feature, please leave a comment.
